# Site 
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Will Reyes
title: Helpdesk Analyst / Cybersecurity Enthusiast 
email: reyeselwil@gmail.com
website: https://willirey.github.io/Resume/



# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: 
github_username:  WilliRey
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
linkedin_username: Will Reyes
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: WilliRey/Resume/images/Profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Will and I'm a Helpdesk Analyst with a strong interest in cybersecurity. I troubleshoot and fix issues for 1000+ end users, I have experience working with Office365, Citrix, Falcon Crowdstrike, Mimecast,
  Azure/Active Directory, remote tools. 
  I am most skilled in: <mark>remote troubleshooting</mark> and <mark>eating pasta</mark>
![tryhackme stats](https://raw.githubusercontent.com/reyeselwil/reyeselwil/master/assets/thm_propic.png)

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Honeypot Lab 
        link: github.com/willirey
        # link_text: Project Website
        additional_links:
          - title:  Willirey/Azure-Honeypot-Lab
            icon: fab fa-github
            url: github.com/WilliRey/Azure-Honeypot-Lab
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          In this lab I use Microsoft Sentinel and Azure to log Failed RDP attempts and plot it attackers IP addresses to a map.
        description: > # this will include new lines to allow paragraphs
          I started this project as a way to gain Azure experience as well as gaining expirience working with logs withing a Siem.
          Additionally, was able to practice a bit using powershell scripts 

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: RWE
        link: rwe.com
        # link_text: rwe.com
        sub_title: Helpdesk Analyst
        caption: October 2023 > Present
        description: | # this will include new lines to allow paragraphs
            As part of the Helpdesk team, I am the first response for users that might be facing hardware or software issues for all of our US locations.
            I am responsible for providing efficient and reliable support while maintaining SLA, and using ManageEngine or Service Now to maintain proper ticketing documentation
      - layout: left
        title: Actylis
        link: Actylis.com
        # link_text: rwe.com
        sub_title: Helpdesk Technician
        caption: October 2021 > October 2023
        description: | # this will include new lines to allow paragraphs
            As a helpdesk Tech at
        
        

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Farmingdale State University
        caption: 2022
        sub_title: Computer Programming and Information Systems (B.S.)
      - layout: left
        title: Nassau Community College
        caption: 2019
        sub_title: Information Technology (A.A.S)  
      - layout: left
        title: Cisco CCNA
        caption: Expire - 
        sub_title: Information Technology (A.A.S) 

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and Cybersecurity some of my other interests and hobbies are:
      - Gym/Working Out
      - Cyberpunk
      - cars
      - MMA


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
