# Site 
repository: WilliRey/Resume
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Will Reyes
title: Helpdesk Analyst / Cybersecurity Enthusiast 
email: reyeselwil@gmail.com
website: https://willirey.github.io/Resume/



# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: 
github_username:  WilliRey
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
linkedin_username: will-reyes-a057b2176
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: TryHackMe
  icon: fas fa-globe
  url: https://tryhackme.com/p/reyeselwil

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/Profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Will and I'm a Helpdesk Analyst with a strong interest in cybersecurity. I troubleshoot and fix issues for 1000+ end users, I have experience working with Office365, Citrix, Falcon Crowdstrike, Mimecast,
  Azure/Active Directory, remote tools. 
  I am most skilled in: <mark>remote troubleshooting</mark> and <mark>eating pasta</mark>


content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Honeypot Lab 
        link: github.com/willirey/Azure-Honeypot-Lab
        # link_text: Project Website
        additional_links:
          - title:  Willirey/Azure-Honeypot-Lab
            icon: fab fa-github
            url: github.com/WilliRey/Azure-Honeypot-Lab
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          In this lab I use Microsoft Sentinel and Azure to log Failed RDP attempts and plot it attackers IP addresses to a map.
        description: > # this will include new lines to allow paragraphs
          I started this project as a way to gain Azure experience as well as gaining expirience working with logs withing a Siem.
          Additionally, was able to practice a bit using powershell scripts 
      
      - layout: top-middle
        title: Homelab 
        link: github.com/willirey/Homelab
        # link_text: Project Website
        additional_links:
          - title:  Willirey/Azure-Honeypot-Lab
            icon: fab fa-github
            url: github.com/WilliRey/HomeLab
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          In this project I use a Lenovo Thinkcentre PC with Proxmox to build my own virtualization server. 
        description: > # this will include new lines to allow paragraphs
          This hands-on setup allows me to explore, experiment, and gain practical experience in a controlled setting,
          enhancing my proficiency in these crucial aspects of IT infrastructure: Virtualization, Network Management, Security and Storage Solutions

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: RWE
        link: rwe.com
        # link_text: rwe.com
        sub_title: Helpdesk Analyst
        caption: October 2023 > Present
        description: | # this will include new lines to allow paragraphs
            As part of the Helpdesk team, I am the first response for users that might be facing hardware or software issues for all of our US locations.
            I am responsible for providing efficient and reliable support while maintaining SLA, and using ManageEngine or Service Now to maintain proper ticketing documentation
      - layout: left
        title: Actylis
        link: Actylis.com
        # link_text: actylis.com
        sub_title: Helpdesk Technician
        caption: October 2021 > October 2023
        description: | # this will include new lines to allow paragraphs
            Efficiently addressed support tickets and provided troubleshooting for the main organization and 14 remote offices across North America, Europe,
            and Asia. Monitored and enhanced performance and security for 150+ hosts and servers using Crowdstrike Falcon, actively detecting and patching vulnerabilities.
            Proactively thwarted phishing attempts through Mimecast email monitoring. Managed IT equipment procurement, documentation, and guide creation while serving
             as the primary contact for Sharepoint/OneDrive requests. Successfully led the migration of on-premises file servers to Sharepoint and transitioned 90+ hosts to Microsoft Intune and Autopilot.
      - layout: left
        title: A & A Industrial
        link: http://www.aanassau.com/
        # link_text: aanassau.com/
        sub_title: Sales Coordinator
        caption: July 2020 > October 2021
        description: | # this will include new lines to allow paragraphs
            Conducted daily consultations with 10+ client companies to ascertain equipment requirements. Collaborated with 20+ distributors to obtain pricing,
            availability information, and manage inventory orders. Addressed basic IT, networking, and software issues in a small office environment.
      - layout: left
        title: Triwire Engineering solutions
        # link: 
        # link_text:
        sub_title: Installation Technician
        caption: December 2019 > July 2020
        description: | # this will include new lines to allow paragraphs
            Modify equipment to improve performance or meet customer specifications. Install communication equipment, including data and telephone lines, wiring,
            network modems, and routers. Effectively troubleshoot an average of 15 daily customer connection issues, prioritizing excellent customer service.
  

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Farmingdale State University
        caption: 2022
        sub_title: Computer Programming and Information Systems (B.S.)
      - layout: left
        title: Nassau Community College
        caption: 2019
        sub_title: Information Technology (A.A.S)  
      - layout: left
        title: Cisco CCNA
        caption: Expires - January 2026
        sub_title: Credential ID CSCO14034172
      - layout: left
        title: Comptia Security+ 
        caption: Expires - July 2025
        sub_title: Credential ID COMP001021102092
      - layout: left
        title: Comptia A+
        caption: Expires - July 2025
        sub_title: Credential ID COMP001021102092

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and Cybersecurity some of my other interests and hobbies are:
      - Gym/Working Out
      - Cyberpunk
      - cars
      - MMA


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
